---
- hosts: myubuntuservers
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt:
     name: "{{myubuntuwebpackage}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: i want to start webserver on ubuntu node only
    service:
      name: "{{myubuntuwebpackage}}""
      state: restarted
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on redhat nodes only
    yum:
     name: "{{myredhatwebpackage}}"
     state: present
    when: ansible_os_family=="RedHat"

  - name: ensure httpd webserver is running on redhat node only
    service:
     name: httpd
     state: started
    when: ansible_os_family=="RedHat" 
