---
- hosts: myubuntuservers
  become: yes
  tasks:
  - name: install java on ubuntu machine
    apt: 
     name: "{{myjavaonubuntu}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: install java on redhat machine 
    yum:
     name: "{{myjavaonredhat}}"
     state: present
    when: ansible_os_family=="RedHat"