---
  - hosts: 172.31.24.85
    become: yes
    vars:
     myvar1: git
     myvar2: tree
     myvar3: wget
    tasks:
     - name: display vars1
       debug:
        msg: "{{myvar1}}" 
     - name: install git
       apt:
         name: "{{myvar1}}"
         state: present